version: "3.9"

services:
  prometheus:
    image: gcr.io/gravitybridge-watch/prometheus:latest
    build:
      context: docker/prometheus
    env_file:
      - .env.local
    volumes:
      - prometheus_data:/prometheus
      - ./docker/prometheus/config/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: gcr.io/gravitybridge-watch/grafana:latest
    build:
      context: docker/grafana
    env_file:
      - .env.local
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/config/etc/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/config/usr/share/grafana/public/dashboards/home.json:/usr/share/grafana/public/dashboards/home.json
    ports:
      - "13000:3000"

volumes:
  prometheus_data:
  grafana_data:
